### ISSUE TITLE
What if there's no built-in Promise?

### ISSUE THREAD

**Issue by mdda** [ahmadnassri/mkdirp-promise#1]
This module would work for a lot more people if you detected whether Promise was available, and required (say) bluebird if not.  

I understand that everyone should be using node>0.12 (as in your package.json), but, at the moment, your README is definitely over-Promising...

**Comment by ahmadnassri** [comment]
was gonna say no, the requirement is clearly defined in `package.json` but your pun won me over.

update coming up.

**Comment by ahmadnassri** [comment]
done with [`v1.0.3`](https://github.com/ahmadnassri/mkdirp-promise/releases/tag/v1.0.3) sorry about the delay ...

**Comment by mdda** [comment]
Just wanted to say thanks : I incorporated it immediately, and it works nicely.

**Comment by ahmadnassri** [comment]
👍

**Comment by chpio** [comment]
you could also use *[any-promise](https://www.npmjs.com/package/any-promise)* and let the app dev decide.
