### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by mbrevda** [ahmadnassri/mkdirp-promise#46]
It would be good to get a changelog so that we know what the braking changes are in major versions. Thanks!

**Comment by ahmadnassri** [comment]
I use the releases history and description as a changelog: https://github.com/ahmadnassri/mkdirp-promise/releases 

which is automatically populated using `semantic-release` (`2.0.0` release wasn't properly tagged, will fix)

let me know if that addresses your concern?

**Comment by mbrevda** [comment]
Yup. Didn't see much activity there and 2.0 didnt have any info. Thanks!
