### ISSUE TITLE
un-break old Node

### ISSUE THREAD

**Issue by mheiber** [ahmadnassri/mkdirp-promise#67]
We're on an ancient Node (v0.12.15) and mkdirp-promise worked great for us until you removed the compile step. Now it fails on `Use of const in strict mode`.

Can you use versioning so we can fall back to a version that works with old Node?

Thanks for your work on this library.

**Comment by ahmadnassri** [comment]
Node `v0.12x` support was removed as it is LTS ends in `2016-12-31`: https://github.com/nodejs/LTS

the engine declaration also states support for only [`>=4`](https://github.com/ahmadnassri/mkdirp-promise/blob/master/package.json#L18)

**Comment by ahmadnassri** [comment]
you can always fix your dependency to `v3.0.1` before the depreciation

**Comment by mheiber** [comment]
whoops. thanks
