### ISSUE TITLE
4.0.0 -> 4.1.0 Borken usage

### ISSUE THREAD

**Issue by albinekb** [ahmadnassri/mkdirp-promise#68]
Hello!

I installed this module at version 4.0.0, (https://github.com/ahmadnassri/mkdirp-promise/tree/v4.0.0)

and there it said:
```js
/*
 * Node 6
 * Built using `babel-preset-es2015-node6`
 */
const mkdirpPromise = require('mkdirp-promise/lib/node6')
```

This is no longer working with version 4.1.0, this change should have been a major bump.

Sorry to say i need to switch out this module since I cannot rely on modules that break functionality with a minor SemVer bump.

Thanks, this is just a heads-up for the future.

**Comment by ahmadnassri** [comment]
indeed, looks like `semantic-release` did not pick up on the breaking message! I'll remove the `4.1` version from npm and release a `5.0`

**Comment by ahmadnassri** [comment]
@albinekb if you're on node6, you didn't even need this module, or any other ... just use mkdir directly.

```
const mkdirp = require('mkdirp')

module.exports = function (dir, opts) {
  return new Promise((resolve, reject) => {
    mkdirp(dir, opts, (err, made) => err === null ? resolve(made) : reject(err))
  })
}
```

**Comment by albinekb** [comment]
Thanks for fixing it so fast 😄  I'll continue to use this then 🎉 

Also, yes i can do like that but i like the simplicity of modules :)
compare that you wrote to
```js
const mkdirp = require('mkdirp-promise')

mkdirp('/foo/bar/')
  .then(console.log)
  .catch(console.error)
```

Maybe I'll take your snippet and make a tiny lib of it 😄

**Comment by ahmadnassri** [comment]
yeah, just throw my snippet into its own file, then you can do `require('./filename.js')`
