### ISSUE TITLE
Typecript support

### ISSUE THREAD

**Issue by ponnex** [ahmadnassri/mkdirp-promise#75]
How do you import it on typescript?

`import * as mkdirp from 'mkdirp-promise';`

says that there is no declaration of sort. As I look at the source code there isn't index.d.ts

**Comment by ahmadnassri** [comment]
PRs welcome! I'm not too deep into typescript world

**Comment by JoshuaKGoldberg** [comment]
Types are available in the `@types/mkdirp-promise` package. ✨
