### ISSUE TITLE
Dependencies accept breaking change to mkdirp, causing library to fail

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [ahmadnassri/mkdirp-promise#87]
The dependency on `mkdirp` in this library is `"*"` ... and `mkdirp`  just published a complete rewrite which completely breaks this package -- 0/4 tests pass.

I _suspect_ this is the source of my woes at https://github.com/microsoft/rushstack/issues/1713

**Comment by AArnott** [comment]
`mkdirp-promise` becomes irrelevant because the 1.0.x release of `mkdirp` itself returns a promise.
So the 'fix' for this should be to republish `mkdirp-promise` with a dependency version constraint of `< 1.0`

**Comment by ahmadnassri** [comment]
see #89
